Draft: introduce mysql/mariadb to pqsl-migration
zammad/zammad-documentation pull request #253
Opened 2022-11-11 16:12 UTC by YetAnotherGerrit

2022-11-18 18:17 UTC, MrGeneration requested changes
I haven't verified the described steps as at least 3 people at Zammad have according to your information. I thus expect them to fit ... I'm missing a lot of time resources...

What I did was to clean up *a lot* of duplicate content and inconsistencies that were also introduced during previous PRs by me.

I'm really no fan of duplicate intros.
We're repeating the same text passages on several parts of the documentation - that's useless if it's the exact same string.

Please consider using includes or choose a different wording for the migration part.
I did unify the rest, I was going to delete the whole intro text from the first paragraph but hesitated. 
![image](https://user-images.githubusercontent.com/6549061/202775044-69d5c2c9-433f-4e6f-a223-fcd825d6b865.png)

2022-11-18 18:17 UTC, MrGeneration commented on appendix/migrate-to-postgresql.rst
> +         $ yum install -y https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-7-x86_64/pgloader-3.6.2-1.rhel7.x86_64.rpm
Something seemed to went wrong here, can you please adjust to the correct package required?
Or however you install it on CentOS.

2022-11-19 09:47 UTC, YetAnotherGerrit commented on appendix/migrate-to-postgresql.rst
> +         $ yum install -y https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-7-x86_64/pgloader-3.6.2-1.rhel7.x86_64.rpm
Works for me on CentOS7 and CentOS8 Stream on fresh Hetzner-Cloud-servers. Can you specify what went wrong?

2022-11-19 21:34 UTC, MrGeneration approved these changes

2022-11-19 21:34 UTC, MrGeneration commented on appendix/migrate-to-postgresql.rst
> +         $ yum install -y https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-7-x86_64/pgloader-3.6.2-1.rhel7.x86_64.rpm
Sorry I can't find what disturbed me yesterday, let's ignore it.

2022-11-19 21:35 UTC, MrGeneration commented on appendix/migrate-to-postgresql.rst
> +         $ yum install -y https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-7-x86_64/pgloader-3.6.2-1.rhel7.x86_64.rpm
Ah wait the wording thing (2 times the same text) still is valid of course.

2022-11-21 07:57 UTC, merged